/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.ShareInfo;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-09-25T02:21:24.943Z")

@Api(value = "shareInfo", description = "the shareInfo API")
public interface ShareInfoApi {

    @ApiOperation(value = "get the shareInfo from server,majority including wechat information.", nickname = "shareInfoGet", notes = "query by openid to find out what this person owes,mainly about the share summary,share description,share images.", response = ShareInfo.class, tags={ "share", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "return the specific share info.", response = ShareInfo.class) })
    @RequestMapping(value = "/shareInfo",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<ShareInfo> shareInfoGet(@ApiParam(value = "find the user's shareInfo by openId.",required=true) @PathVariable("openId") String openId);


    @ApiOperation(value = "Create a shareInfo.", nickname = "shareInfoPost", notes = "", tags={ "share", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "valid response."),
        @ApiResponse(code = 400, message = "parameter error."),
        @ApiResponse(code = 405, message = "method not allow.") })
    @RequestMapping(value = "/shareInfo",
        method = RequestMethod.POST)
    ResponseEntity<Void> shareInfoPost(@ApiParam(value = "find the user's shareInfo by openId." ,required=true )  @Valid @RequestBody ShareInfo shareInfo);

}
